#!/bin/bash

#PBS -l nodes=1:ppn=8
#PBS -l mem=32gb
#PBS -l walltime=12:00:00
#PBS -q short
#PBS -j oe
#PBS -o /home/vitor/hlapers/1-make_indices/indices/star_index_log.txt

cd $PBS_O_WORKDIR

indexDIR=./star
fasta=../data/gencode/gencode.v25.MHC.IMGT.transcripts.fa

mkdir -p $indexDIR

STAR --runThreadN $PBS_NUM_PPN --runMode genomeGenerate --genomeDir $indexDIR\
  --genomeFastaFiles $fasta --genomeChrBinNbits 10 --genomeSAindexNbases 11
