#!/bin/bash

#PBS -l nodes=1:ppn=12
#PBS -l mem=32gb
#PBS -l walltime=12:00:00
#PBS -q short
#PBS -j oe
#PBS -o ~/hlatx/1-make_indices/log/mhc.log

STAR=~/STAR

indexDIR=./mhc_index
fasta=./gencode/gencode.v25.MHC.IMGT.transcripts.fa

cd $PBS_O_WORKDIR

mkdir -p $indexDIR

$STAR --runThreadN 12 --runMode genomeGenerate --genomeDir $indexDIR\
  --genomeFastaFiles $fasta --genomeChrBinNbits 10 --genomeSAindexNbases 11
